version: "3"

services:
  chatgpt_web:
    container_name: chatgpt_web
    restart: always
    env_file:
      - .env
    ports:
      - 127.0.0.1:5173:5173
    volumes:
      - .:/app
    build:
      context: "."
      dockerfile: Dockerfile
